### ISSUE TITLE
Export as PDF/HTML - Wont Show the Icon

### ISSUE THREAD

**Issue by xmarkclx** [libeanim/inkdrop-admonition#15]
# PDF
<img width="197" alt="image" src="https://user-images.githubusercontent.com/5523580/177023918-61fd41d8-cfb5-4938-90b2-f44336144e98.png">

# HTML
<img width="153" alt="image" src="https://user-images.githubusercontent.com/5523580/177023927-af2c2755-abd1-4149-9e61-ea6b47041369.png">

**Comment by drank-sinatra** [comment]
I have experienced the same.

**Comment by purnasatria** [comment]
i have same experience..but i found a workaround to handle this..

admonition use FontAwesome for the icon
```css
.admonition-icon {
    position: absolute;
    left: 1.2rem;
    font-family: "FontAwesome";
    font-style: normal;
    font-weight: 400;
    font-size: 24px;
    // font-size: 1.7rem;
    // width: 1.8rem;
    width: 24px;
    display: inline-block;
    line-height: 1;
    text-transform: none;
    letter-spacing: normal;
    text-align: center;
    word-wrap: normal;
    white-space: nowrap;
    direction: ltr;
    /* Support for all WebKit browsers. */
    -webkit-font-smoothing: antialiased;
    /* Support for Safari and Chrome. */
    text-rendering: optimizeLegibility;
    /* Support for Firefox. */
    -moz-osx-font-smoothing: grayscale;
    /* Support for IE. */
    font-feature-settings: 'liga';
}
```
---
for the icon to be recognized in the **HTML**, you can install FontAwessome font
in ubuntu you can run command 
```sh
sudo apt-get install fonts-font-awesome
``` 
---
for the **PDF**, you can insert custom css setting for PDF print 
see this [documentation](https://docs.inkdrop.app/manual/style-tweaks#applying-custom-styles-for-printing) for the detail

the css will look like this
```css
@media print {
  .admonition-icon {
    position: absolute;
    left: 1.2rem;
    font-family: "FontAwesome";
    font-style: normal;
    font-weight: 400;
    font-size: 24px;
    // font-size: 1.7rem;
    // width: 1.8rem;
    width: 24px;
    display: inline-block;
    line-height: 1;
    text-transform: none;
    letter-spacing: normal;
    text-align: center;
    word-wrap: normal;
    white-space: nowrap;
    direction: ltr;
    /* Support for all WebKit browsers. */
    -webkit-font-smoothing: antialiased;
    /* Support for Safari and Chrome. */
    text-rendering: optimizeLegibility;
    /* Support for Firefox. */
    -moz-osx-font-smoothing: grayscale;
    /* Support for IE. */
    font-feature-settings: 'liga';
  }
}
```
